//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace AssemblyCSharp
{
	public class GlobalValue
	{
		public GlobalValue ()
		{
		}

		public static float AllSpeedIncrementGround = 5.5f;

		public static float START_SPEED_GROUND = 6.0f;

		public const float NORMAL_SPEED_GROUND = 7.0f;

		public const float HARD_SPEED_GROUND = 8.0f;

		public const float VERY_HARD_SPEED_GROUND = 10.0f;

		public const float EXTREMLY_HARD_SPEDD_GROUND = 14.0f;

		public const string CHARACTER_SELECTED_INDEX = "CharacterSelected";

		public const string POINTS_COUNT = "Points Count";

		public const string KEY_CHARACTER_LOCK_INDEX = "CharacterLockIndex";

		public const int CHARACTER_LOCKED_INDEX = 2;

		public const int TOTAL_COIN_UNLOCK = 99;

		public const string PACKAGE_NAME = "com.darkmoon.runtapjump";
	}
}

